# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql2
  database: Blogspot_development
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: root

